### PR TITLE
Adding an exit command

### PR DESCRIPTION
**Pull request by alexdaube**
First of all, very cool project! Thank you very much for this.

Couldn't exit the process without closing the actual tab, which I personally find annoying. Thought adding an exit command would be a nice touch. Added the "q" key as the exit command.

### CODE REVIEW

**Comment by laggingreflex** [comment]
Thanks! Glad you like it!

Isn't this already possible with <kbd>Ctrl</kbd><kbd>C</kbd> though?

**Comment by alexdaube** [comment]
I retried it just to make sure I wasn't acting the fool, haha. <kbd>Ctrl</kbd><kbd>C</kbd> doesn't seem to go through with mochista on my environment (bash + macOs). Thought <kbd>q</kbd> would be a natural solution for those like me  that have this particular problem.

**Comment by laggingreflex** [comment]
Sorry, my bad. I never actually noticed that this didn't work (I use conemu which force-terminates processes). 

Merged this and also made <kbd>Ctrl</kbd><kbd>C</kbd> work in https://github.com/laggingreflex/mochista/pull/10. 

Released as 0.10.1. Please check it out and let me know. Thanks!

**Comment by alexdaube** [comment]
Awesome! Works great. I was about to try to refactor it to make it work with <kbd>Ctrl</kbd><kbd>C</kbd> but you beat me to it 😄 . I guess listening to keypress throws default behaviour out the window, which makes sense I suppose.

**Pull request merged**
